dbt_playground:
    target: dev
    outputs:
        dev:
            type: postgres
            host: "localhost"
            user: "postgres"
            password: "postgres"
            port: 32768
            dbname: "postgres"
            schema: "public"
            threads: 5